language: objective-c
env:
  - PLATFORM=android
script:
  - /bin/bash -xe ./runIntegrationTests.sh
before_install:
  - sudo gem install compass
  - npm install -g grunt-cli bower cordova ios-sim
  - npm install
  - npm test