language: objective-c
env:
  - PLATFORM=android
script:
  - /bin/bash -xe ./runIntegrationTests.sh
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
  - echo $JAVA_HOME
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer \
      | bash /dev/stdin --install=build-tools-21.0.1,android-21,sys-img-armeabi-v7a-android-21 \
      && source ~/.android-sdk-installer/env
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
   emulator -avd test -no-skin -no-audio -no-window > /dev/null 2>&1 &
  - npm install -g cordova@latest
  - npm install
  - npm test